### ISSUE TITLE
Global tool looking in incorrect path

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/cli#10803]
A bug was opened in Roslyn against the dotnet-format (https://github.com/dotnet/roslyn/issues/33414) where the cli is using the wrong path when running the global tool.

## Steps to reproduce
Install the 3.0.0 release version of the dotnet-format global tool.
Run `dotnet-format -?`

## Expected  behavior

The app help would be displayed.

## Actual behavior

```
~\source\repos> dotnet-format -?
The application to execute does not exist: 'C:\Users\jorobich\.dotnet\tools\.store\dotnet-format\3.0.0-beta4-19105-10\dotnet-format\3.0.0-beta4-19105-10\tools\netcoreapp2.1\any\dotnet-format.dll'.
```

The application is installed under a 3.0.0 folder.

![image](https://user-images.githubusercontent.com/611219/52877170-29142500-310e-11e9-80fc-035505190a86.png)

The nuspec lists the version as 3.0.0.

![image](https://user-images.githubusercontent.com/611219/52877237-4d700180-310e-11e9-975c-ad084574974c.png)

## Environment data
`dotnet --info` output:

```
~\source\repos> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-alpha1-009706
 Commit:    a2c490c483

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-alpha1-009706\

Host (useful for support):
  Version: 3.0.0-preview1-27024-03
  Commit:  0764a87431
```

**Comment by JoeRobich** [comment]
I meant to add that this package installs and works fine from v2.1.8 of the CLI.

```
jorobich@jorobich-vm1:~/Source/ConsoleTest$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.504
 Commit:    91e160c7f0

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.504/

Host (useful for support):
  Version: 2.1.8
  Commit:  209f8aa25c

.NET Core SDKs installed:
  2.1.504 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by livarcocc** [comment]
@JoeRobich could you try this on a newer build of the SDK?

You are still using `3.0.100-alpha1-009706` which is very old. The version here that matters to us is the `.NET Core SDK (reflecting any global.json)` version. Please try out with a nightly preview3 build available at dotnet/core-sdk or a nightly preview4.

**Comment by livarcocc** [comment]
cc @wli3

**Comment by sohanlalpareek** [comment]
Need my ip addressLeave a comment

**Comment by sohanlalpareek** [comment]
ctrl +1Leave a comment

**Comment by sohanlalpareek** [comment]
Leave a comment

**Comment by wli3** [comment]
It should be smilar to https://github.com/dotnet/cli/issues/10459. It should be fixed in latest SDK

**Comment by livarcocc** [comment]
@wli3 can you confirm and close this issue if that's the case?

**Comment by wli3** [comment]
will do on Tuesday

**Comment by JoeRobich** [comment]
I am still seeing this issue with the preview 4 sdk installed. I unlisted the 3.0.0 release and so am installing the nupkg locally.

```
~\Desktop> dotnet tool install -g dotnet-format --add-source .
You can invoke the tool using the following command: dotnet-format
Tool 'dotnet-format' (version '3.0.0') was successfully installed.

~\Desktop> dotnet format
The application to execute does not exist: 'C:\Users\jorobich\.dotnet\tools\.store\dotnet-format\3.0.0-beta4-19105-10\dotnet-format\3.0.0-beta4-19105-10\tools\netcoreapp2.1\any\dotnet-format.dll'.

~\Desktop> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview4-010381
 Commit:    a7c15a2539

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview4-010381\

Host (useful for support):
  Version: 3.0.0-preview4-27418-3
  Commit:  6d5e4a7932
```

the dotnet-format.exe generated on install is still getting built using a different version string in the path.

![image](https://user-images.githubusercontent.com/611219/53035998-9b954580-342b-11e9-85b4-4531d03cbed4.png)

The path doesn't match the assembly version or assembly file version. It does match the beginning of the AssemblyInformationalVersion.

![image](https://user-images.githubusercontent.com/611219/53036829-7efa0d00-342d-11e9-89b0-c18785b563f1.png)

I did find in the dotnet-format.deps.json the same version string being used by the executable

![image](https://user-images.githubusercontent.com/611219/53036924-bc5e9a80-342d-11e9-8bd8-a5b24bb1f033.png)

**Comment by JoeRobich** [comment]
This issue was due to how Roslyn builds and packages it's NuGet artifacts. The shim executables were not being regenerated appropriately.
