### ISSUE TITLE
Failed to initialize CoreCLR, HRESULT: 0x80131500

### ISSUE THREAD

**Issue by murali2020kris** [dotnet/cli#2018]
## Steps to reproduce
1. Download https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/Latest/dotnet-dev-centos-x64.latest.tar.gz
2. Unpack tar file 
3. Set DOTNET_HOME as unzipped folder. [usr/share/dotnet]
4. Change permission settings for unzipped folder dotnet
5. run dotnet -version

## Expected  behavior
Should give version number

## Actual behavior
Gives error message Failed to initialize
Failed to initialize CoreCLR, HRESULT: 0x80131500

## Environment data
`dotnet --version` output:
Failed to initialize CoreCLR, HRESULT: 0x80131500

**Comment by ellismg** [comment]
Have you installed dependent packages like icu and libunwind?

**Comment by murali2020kris** [comment]
@ellismg Thank you so much. icu was missing. It works now.

**Comment by ellismg** [comment]
Glad to hear it!

**Comment by Bundas** [comment]
Hey, I have the same error. I have icu and libundwind installed. What else could be the problem?

I am running Ubuntu 16.04 @ellismg @murali2020kris

**Comment by decompiled** [comment]
@Bundas I am also having the same issue with 16.04 with icu and libundwind.

**Comment by ellismg** [comment]
Support for 16.04 will come at RTM.

**Comment by vstoykov** [comment]
I also has the same problem. I'm trying it on Fedora 23 (downloaded Centos binaries). 

I know that Fedora is not listed in supported distributions but I just wanted to try. Probably the reason for error is the same as for Ubuntu 16.04 (version of the `icu` is newer in Fedora 23 and Ubuntu 16.04, compared to Debian 8, CentOS 7 and Ubuntu 14.04)

**Comment by robert-sandor** [comment]
For Ubuntu 16.04, installing libicu52 from trusty-security seems to fix the problem.

**Comment by r105m** [comment]
For Fedora you can copy necessary libs from.  ftp://195.220.108.108/linux/centos/7.2.1511/os/x86_64/Packages/libicu-50.1.2-15.el7.x86_64.rpm

**Comment by capote** [comment]
Any ideas for this in OpenSUSE Leap?  I've installed the package icu and libicu52_1 and get this same issue.

**Comment by icebreaker** [comment]
You can find out _what_ is **missing** by running:

```bash
find /opt/dotnet -name '*.so' -type f -print | xargs ldd | grep 'not found'
```

Replace `/opt/dotnet` with the directory you "un-tarred" the tar ball to.

**Comment by capote** [comment]
Thanks @icebreaker 

It appears I'm still missing libicu53 (seems unavailable for Leap) and liblldb.so.3.5.0 (I have 3.7.0 installed--is 3.5.0 specifically required?)

**Comment by kamathba** [comment]
Same problem on Fedora 24, with the following library versions:
libunwind-1.1-11.fc24.x86_64
libicu-56.1-4.fc24.x86_64

**Comment by capric8416** [comment]
openSUSE Tumbleweed:
sudo find /opt/dotnet -name '*.so' -type f -print | xargs ldd | grep 'not found'
        liblldb.so.3.5.0 => not found         # liblldb.so.3.8 found
        libicuuc.so.53.1 => not found       # libicuuc.so.57.1 found
        libicui18n.so.53.1 => not found    # libicui18n.so.57.1 found
        liblttng-ust.so.0 => not found        # not found

**Comment by r105m** [comment]
kamathba, on fedora 24 you need libicu from fedora 23. Try that package: mirror.yandex.ru/fedora/linux/releases/23/Workstation/x86_64/os/Packages/l/libicu-54.1-5.fc23.x86_64.rpm

**Comment by 3rdey3** [comment]
Arch Linux
sudo find /opt/dotnet -name '*.so' -type f -print | xargs ldd | grep 'not found'
/opt/dotnet/shared/Microsoft.NETCore.App/1.0.0/System.Net.Http.Native.so: /usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /opt/dotnet/shared/Microsoft.NETCore.App/1.0.0/System.Net.Http.Native.so)
	libicuuc.so.52 => not found
	libicui18n.so.52 => not found
	liblldb-3.6.so => not found
	liblttng-ust.so.0 => not found

**Comment by capote** [comment]
Okay, I don't think it's so productive if we all just post our missing dependencies here.  We need to find out if they require those particular versions for every distribution, or if a specific version per distribution is needed, or if it simply doesn't work on some distributions (I don't think I've seen a successful OpenSUSE or Arch install yet).  Any ideas?

**Comment by iDev0urer** [comment]
Had the same problem running Kali linux. Turned out that I had a newer version of libicu and libicu-dev installed (v55 I believe) and dotnet wanted version 52. All I had to do was go to the debian repos and find libicu52 and libicu52-dev and install them

**Comment by vanthome** [comment]
Gentoo User here. I have 57.1 of libicu installed. @iDev0urer did downgrading to 55.x help in your case?

**Comment by heavendragon** [comment]
Opensuse 42.1 finally success after install libicu from this https://software.opensuse.org/package/libicu53_1

**Comment by capote** [comment]
@heavendragon Interesting; I installed the rpm from that link (and it's one dependency it asked me for) and it runs fine for me.  dotnet new, restore, and run all worked as expected.  Getting into this some more tomorrow.

**Comment by iDev0urer** [comment]
@vanthome I downgraded to v52 and now it works. At the very least I'm not getting that error when typing `dotnet --help` and `dotnet --version` anymore. I haven't tried doing anything else with it yet

**Comment by tgoncuoglu** [comment]
here are some specifics: OS is Fedora 24 with libunwind/libicu installed (f24 has icu at version 56.1 and libunwind at version 1.11). I'm getting above mentioned error. Downgrading to f23 libicu is not an option because of dependencies involved: qt5-qtbase, among others. No can do. So in the end, it seems dotnet requires a specific icu version, ie v52.

**Comment by kamathba** [comment]
I was able to get it working on Fedora 24 by building/installing libicu v52 from source and installing liblldb /libunwind using yum

**Comment by sphildreth** [comment]
On Fedora 24 I installed ftp://195.220.108.108/linux/fedora/linux/releases/23/Everything/x86_64/os/Packages/l/libicu-54.1-5.fc23.x86_64.rpm and "dotnet -version" worked.

**Comment by mschlechter** [comment]
RTM is out now, but still not working with Ubuntu 16.04 on my machine. I've got libicu version 55.1-7 installed instead of 53.1, which seems to be the deal breaker.

**Comment by mickaelistria** [comment]
Another way to get it running on Fedora 24 and other distros using too recent ICU (provided to me by @scela) 

1. download libicu-54.1-5.fc23.x86_64.rpm from wherver ( eg http://mirror.yandex.ru/fedora/linux/releases/23/Workstation/x86_64/os/Packages/l/libicu-54.1-5.fc23.x86_64.rpm )
2. open it with archive manager, go to ./usr/lib64 and extract all the .so files to ~/oldicu
3. now execute:  `LD_LIBRARY_PATH=~/oldicu/:$LD_LIBRARY_PATH dotnet` instead of invoking directly `dotnet`.  

This has the advantage of not forcing installation of older icu (which can lead to other issues for package requiring newer icu). Also I imagine this would work with any Linux distribution facing this issue. You can also tweak your .bashrc to define `alias dotnet=LD_LIBRARY_PATH=~/oldicu/:$LD_LIBRARY_PATH dotnet`, but since alias aren't inherited, it's not working when running scripts, so one had to use `source script.sh` instead of `./script.sh` if they want to take advantage of their alias.

**Comment by mrmeek** [comment]
I was able to dotnet new, restore, and run on OpenSUSE 42.1 by downloading and installing the dependency for libicu53_1: https://github.com/dotnet/cli/issues/2018 (this just copies libicudt531.dat to/usr/share/icu/53.1), and using the technique mickaelistria described such that I can leave the default 52_1 install alone. Thanks mickaelistria!

BTW, Kernel v4.1.20-11-default

**Comment by molaie** [comment]
for debian stretch users, there is more than just `libicu52`.
I added this line to sources.list (/etc/apt/sources.list)
`deb http://ftp.de.debian.org/debian/ jessie main`
then : 
`apt-get update`
finally:
`apt-get -t jessie install libicu52`
`apt-get install libssl1.0.0`
in this point, the command by @icebreaker gives this output:

        root@yspdebian:~# find /opt/dotnet -name '*.so' -type f -print | xargs ldd | grep 'not found'`

        liblldb-3.6.so => not found

        liblttng-ust.so.0 => not found
finally, work is done by :
`apt-get install liblttng-ust0` and `apt-get install liblldb-3.6`

and now, i have this error:

    ahmad@yspdebian:~/oldicu$ dotnet new

```
Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.
Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include commandline arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.
Configuring...
-------------------
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 4369 ms
Expanding 0%Segmentation fault
```

**Comment by ellismg** [comment]
There was a bug in 1.0.0 that manifested itself in this way on newer kernels (IIRC it was 4.6.0+) .  We fixed the bug see (https://github.com/dotnet/coreclr/pull/6027) but I don't think the fix has flowed to any of the binary packages.

We will release this fix as part of a 1.0.1 release, but we don't know the exact date of that release yet.  If you want to try the following, it should probably address your issue.

1) Download https://dotnet.myget.org/F/dotnet-core/api/v2/package/runtime.debian.8-x64.Microsoft.NETCore.Runtime.CoreCLR/1.0.4
2) Unzip it to some folder (otherwise it will litter files over whatever folder you extract it in).
3) copy all the files in runtimes/debian.8-x64/native/ to /opt/dotnet/shared/Microsoft.NETCore.App/1.0.0/ (replacing the versions that already exist there).

Give it another whirl after this.

**Comment by molaie** [comment]
`dotnet new` is done, but this time, i have error in `dotnet restore`.
for the first time it does the job, but then in `dotnet run`, i have segfault.
and now, both of them ( `restore` and `run` ) gave segfault.

**Comment by cgountanis** [comment]
Followed instructions for openSuse and I get the same error Failed to initialize CoreCLR, HRESULT: 0x80131500 even when doing --version. Can the instructions be updated, not really going to spend time trying a million different options.

**Comment by jamasu** [comment]
mrmeek could you explain how you followed the instructions in detail? 
I downloaded and installed libicu53 but still getting the errors. I am using openSuse Leap 42.1

**Comment by cgountanis** [comment]
Personally I just gave up ain't nobody got time for that.

**Comment by jamasu** [comment]
we just have to wait for a new release with the bugfix i suppose?

**Comment by jamasu** [comment]
aah, i actually made it work now, just runned sudo zypper remove icu, which removes 52.1 then sudo zypper install icu which installs 53.1 and just like that it works :)

**Comment by cgountanis** [comment]
Great news! Thanks for sharing.

**Comment by mleu** [comment]
@cgountanis based on all the valuable info in this issue I managed to get dotnet running on openSUSE Tumbleweed 20160831 like so:

Install a old libicu 53.1 to $HOME/.icu53
```
wget http://download.opensuse.org/repositories/devel:/languages:/R:/released/openSUSE_Factory/x86_64/libicu53_1-53.1-70.1.x86_64.rpm
rpm2cpio libicu53_1-53.1-70.1.x86_64.rpm | cpio -idmv # unpack
mv usr/lib64 $HOME/.icu53
```

Install the data for the old libicu 53.1 to $HOME/.icu53-data
```
wget http://download.opensuse.org/repositories/devel:/languages:/R:/released/openSUSE_Factory/noarch/libicu53_1-ledata-53.1-70.1.noarch.rpm
rpm2cpio libicu53_1-ledata-53.1-70.1.noarch.rpm | cpio -idmv
mv usr/share/icu/53.1 $HOME/.icu53-data
```

Grab the updated CoreCLR packages [mentioned above](https://github.com/dotnet/cli/issues/2018#issuecomment-239307088) required for newer Linux kernels
```
wget  https://dotnet.myget.org/F/dotnet-core/api/v2/package/runtime.opensuse.13.2-x64.Microsoft.NETCore.Runtime.CoreCLR/1.0.4
unzip 1.0.4.zip
chmod u+r runtimes/opensuse.13.2-x64/native/*
cp runtimes/opensuse.13.2-x64/native/* $(dirname $(command -v dotnet))/shared/Microsoft.NETCore.App/1.0.0/
```

Call dotnet with the old icu plus its data and it should (hopefully) work
```
LD_LIBRARY_PATH="$HOME/.icu53" ICU_DATA="$HOME/.icu53-data" dotnet --version
```

**Comment by cgountanis** [comment]
Thank you I'll give it a shot in the morning.

**Comment by cgountanis** [comment]
Issue with steps:

mv usr/share/icu/53.1 $HOME/.icu53-data
mv: cannot stat ‘usr/share/icu/53.1’: No such file or directory

I am just not that interested to figure it all out. I can wait for them to update the runtime to work on current versions of Linux.

**Comment by cgountanis** [comment]
Scott has some nice instructions over and beyond although it is for Ubuntu 14.04, I can live with that.

http://www.hanselman.com/blog/CommentView.aspx?guid=07154069-1364-4C3E-A776-62CF042E40C7#671298ff-b399-493a-89f7-0c1656145038

**Comment by lnu** [comment]
@mleu Followed your advice and it works.

**Comment by robertmsale** [comment]
@mleu Thanks to you I am now able to use .NET Core. What I did differently was had all of the library files extracted to $HOME/dotfix instead of my home folder, then created a shell script that launches the library path fix taking arguments and placed it in my /usr/local/bin folder so all I have to do is use 

`dotfix`

Instead of dotnet. Thank you!

**Comment by mmisztal1980** [comment]
Experiencing a similar issue on Ubuntu 16.04:

```
mmisztal@ubuntu:/agent$ sudo apt-get install libunwind8
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libunwind8 is already the newest version (1.1-4.1).
libunwind8 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 191 not upgraded.
mmisztal@ubuntu:/agent$ sudo apt-get install icu
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package icu
mmisztal@ubuntu:/agent$ sudo apt-get install libicu55
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libicu55 is already the newest version (55.1-7).
libicu55 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 191 not upgraded.
mmisztal@ubuntu:/agent$ ./config.sh
Failed to initialize CoreCLR, HRESULT: 0x80131500
```

Can anyone advise on how to proceed to get this working? (I'm trying to configure a VSTS build agent on linux)

**Comment by mmisztal1980** [comment]
This seems to have solved my issue :/
```
wget http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu52_52.1-8ubuntu0.2_amd64.deb
sudo dpkg -i libicu52_52.1-8ubuntu0.2_amd64.deb
```

**Comment by EtienneBruines** [comment]
Same goes for Ubuntu 16.10 with libicu52 installed :-(

**Comment by GBatault** [comment]
I am on Fedora 24 : I use a script wich force LD_LIBRARY_PATH, works good for dotnet run. Now I am lost in Visual Studio Code : where do I configure the path of .NET CLI ?

**Comment by nibbles-** [comment]
Just upgraded to Fedora25 (libicu 57.1) and now it is broken again

**Comment by piotrpMSFT** [comment]
@DustinCampbell can you comment on

> I am on Fedora 24 : I use a script(SH) wich force LD_LIBRARY_PATH, works good for dotnet run. Now I am lost in Visual Studio Code : where do I configure the path of .NET CLI ?

@ellismg any updates on this issue? Seems like it's still affecting a bunch of folks...

**Comment by ellismg** [comment]
> any updates on this issue? Seems like it's still affecting a bunch of folks...

We took fixes for vNext (they didn't make it in for 1.1) that should help here.  Basically we added a mode where we can compile in a way such that we'll "roll forward" to newer ICUs.  I believe the plan is to cut over to that mode as the default before vNext for the binaries that we build and distribute.

In the mean time, you can install an older version of libicu or if it's possible to override the version of the CLI that VSCode uses to use a local copy of .NET Core, we have scripts that will let you rebuild the relevant native components.

When I last looked, it was unclear if VSCode was deploying their stuff as shared framework apps or standalone.  Either way, we can do the rebuilds.  If VS Code is just using the shared framework, we have scripts now that can automate the rebuilding.  If they publish their tools standalone, then folks will have to rebuild "by hand".

There may also be problems with some other native components (specifically Crypto and HTTP) but you hit the ICU issues first, since globalization is used early in app startup.

**Comment by DustinCampbell** [comment]
@GBatault: If I understand, you have a script that sets LD_LIBRARY_PATH and launches 'dotnet'? If so, putting this script on your path and naming it 'dotnet' should get various commnads in VS Code that depend on the .NET CLI working.

**Comment by GBatault** [comment]
@DustinCampbell Tanks for the trick : So what I did today : I use my .bashrc add an alias : `dotnet='LD_LIBRARY_PATH=~/oldicu/:$LD_LIBRARY_PATH dotnet'`

But still the error on launching VS Code :
`The .NET CLI tools cannot be located. .NET Core debugging will not be enabled. Make sure .NET CLI tools are installed and are on the path.`

**Comment by DustinCampbell** [comment]
@gregg-miskelly: do you have any ideas?

**Comment by gregg-miskelly** [comment]
@GBatault I don't know enough about how node spawns processes to say for sure if bash aliases will apply or not. Did you try starting VS Code from a bash prompt with the alias set? I would imagine you could at least make a `dotnet` file which is really a bash script that could work.

For reference, all the debugger does is run [`dotnet --info`](https://github.com/OmniSharp/omnisharp-vscode/blob/034d44ede447a73ebb2bdaf32fd2584ff6c3898b/src/coreclr-debug/util.ts#L106).

**Comment by GBatault** [comment]
@gregg-miskelly Tanks, seems to work like this : Create a srcipt shell to launch VS Code whith : `LD_LIBRARY_PATH=~/oldicu/:$LD_LIBRARY_PATH code`

**Comment by pichardoJ** [comment]
I'm running Fedora 25 and `dotnet -version` fails with:

    Failed to initialize CoreCLR, HRESULT: 0x80131500

It seems that I'm missing:

    libicuuc.so.56 => not found
    libicui18n.so.56 => not found

But when I try to install `libicuuc.so.56` using the rpm from [rpmfind](https://rpmfind.net/linux/rpm2html/search.php?query=libicuuc.so.56) it says that it has conflicts with `libicuuc.so.57`

**Comment by voidEMP** [comment]
I'm currently struggling with a icu installation, these libs are missing:
`	liblttng-ust.so.0 => not found
	libicuuc.so.50 => not found
	libicui18n.so.50 => not found
	libcrypto.so.10 => not found
	libssl.so.10 => not found
	liblldb.so => not found
	liblttng-ust.so.0 => not found
	libicuuc.so.50 => not found
	libicui18n.so.50 => not found
	liblldb.so => not found
	libcrypto.so.10 => not found
	libssl.so.10 => not found
`
And when I try to install any of them 
`E: Couldn't find any package by glob 'liblttng-ust.so.0'
E: Couldn't find any package by regex 'liblttng-ust.so.0'
`

**Comment by pichardoJ** [comment]
For Fedora 25 I got it working with this [new copr repo](https://copr.fedorainfracloud.org/coprs/nmilosev/dotnet-clean/).

**Comment by acastaner** [comment]
Downloaded version 1.0.4, followed all the instructions from https://www.microsoft.com/net/core#linuxfedora (although I'm using Fedora 25) and I get the same error:

```
[acastaner@localhost ~]$ dotnet --version
Failed to initialize CoreCLR, HRESULT: 0x80131500
```

I'm apparently missing dependencies

```
[acastaner@localhost ~]$ find /opt/dotnet -name '*.so' -type f -print | xargs ldd | grep 'not found'
	libicuuc.so.56 => not found
	libicui18n.so.56 => not found
	liblldb.so.3.8.0 => not found
```

So it seems that contrary to the statements in this issue the problem seems to still exist? Is there a planned fix rather than the provided workarounds?

**Comment by ellismg** [comment]
It is fixed in master now, if you download 2.0 nightlies from dotnet/cli things should work.

There are no plans to back port the changes to 1.0 or 1.1.

**Comment by gforceg** [comment]
@ellismg, when does 2.0 drop? I'd like to use a version of the CLI that is recommended for production environments. I'd also like to develop on Fedora 25.

**Comment by gforceg** [comment]
@ellismg, I figured it out. Yay!

Downloaded libicu version 56 for fedora 24 (https://fedora.pkgs.org/24/fedora-x86_64/libicu-56.1-4.fc24.x86_64.rpm.html)

I unzipped the .rpm file and copied the library files into /lib64. All works! I need to learn how to download files w/o installing them via dnf... if that's even a thing. I don't like the idea of downloading the libs from a 3rd party website.

**Comment by ellismg** [comment]
> @ellismg, when does 2.0 drop? I'd like to use a version of the CLI that is recommended for production environments. I'd also like to develop on Fedora 25.

The [Roadmap](https://github.com/dotnet/core/blob/master/roadmap.md) says Q3 of this year.

> How do I find out where the CLI is looking for these libs? I wonder if I can make a symlink to the (newer) versions I have installed.

To answer the question, although I now see you've fixed the issue, CoreCLR just does normal probing like any other application would to find these libraries, so that will usually be configured with [ldconfig](http://man7.org/linux/man-pages/man8/ldconfig.8.html).  The problem with making a symlink (vs downloading the libraries as you did) is that ICU decorates function exports with a version number (so instead of an export named "foo" on ICU 51 and 52 it's named "foo_51" and "foo_52" on the two versions) so you need to install a matching version.

.NET Core 1.1 does support Fedora 24 in production, so that's always an option if you need to stick with Fedora and also want to be in a supported place.  I would encourage you to kick the ties on some of the newer 2.0 builds, while we still have time to address any feedback you'll find.

**Comment by knocte** [comment]
thanks @mmisztal1980 , that has solved the issue for me in Ubuntu 16.04.

**Comment by gideondsouza** [comment]
Ok, this still exists for me on Fedora 25. I have libicu and I have libunwind. When I installed them with dnf it says it's already installed.

Any clues or pointers?

**Comment by mickaelistria** [comment]
On Fedora 25, you could have a look to:
* https://copr.fedorainfracloud.org/coprs/nmilosev/dotnet-sig/ which
provides working dotnet-core 1.1 rpm
* the "Linux" binary from
https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.0-preview1-download.md
which is working for me without noticeable tweek (I believe ;).

**Comment by ellismg** [comment]
@gideondsouza Which version of the CLI are you trying to install?

**Comment by gforceg** [comment]
@gideondsouza I'm also running Fedora 25, but I had to install the version of libicu used by Fedora 24 for the CLI to work. (libicu v 56).

**Comment by daddykotex** [comment]
On Ubuntu 16.04, I had:
```
find /opt/dotnet -name '*.so' -type f -print | xargs ldd | grep 'not found'
	libicuuc.so.52 => not found
	libicui18n.so.52 => not found
	liblldb-3.6.so => not found
	libicuuc.so.52 => not found
	libicui18n.so.52 => not found
	liblldb-3.6.so => not found
```

so I did:
```
sudo echo "deb http://security.ubuntu.com/ubuntu trusty-security main" >> /etc/apt/sources.list
sudo apt-get update && sudo apt-get install libicu52 liblldb-3.6
```

**Comment by agrcrobles** [comment]
On Ubuntu 16.04 I ended up symlinking `libicuuc.so.52` `libicui18n.so.52` from `opt` to `usr/lib` as a workaround, I am still looking for a better way to do it though.

**Comment by sunnystormy** [comment]
Is there a reason dotnet Core isn't being built with the latest packages from Debian? libicu52 and liblldb-3.6, for example, are several generations behind. I don't want to have to necro old packages just to get this to run.

**Comment by knocte** [comment]
> Perhaps that should be updated?

@sunnystormy what should be updated? Maybe you want to create a PR since this issue is marked as closed (not sure why though).

**Comment by sunnystormy** [comment]
@knocte Good point. I'll create a new ticket with the contents of the second part of my post.
