### ISSUE TITLE
Asp.Net Core RC2 Error in visual studio 2015

### ISSUE THREAD

**Issue by liuhaoyang** [dotnet/cli#3064]
I am using Visual Studio Enterpirse 2015  Version 14.0.25123.00 Update 2.

I am getting error message after installing DotNetCore.1.0.0.RC2-VS2015Tools.Preview1.

The error message says:
"The project is configured to use .NET Core SDK version 1.0.0-preview1-002702 which is not installed or cannot be found. These components are required to build and run this project."

What should I do now? Looking forward to your reply.

**Comment by ShaomingCode** [comment]
please workspace run  dotnet --version

**Comment by mwiedemeyer** [comment]
Same issue here. Here is the output of `dotnet --version`
![image](https://cloud.githubusercontent.com/assets/4295189/15315772/eb1b5040-1c19-11e6-8f81-8500f80cc123.png)

**Comment by jakvike** [comment]
Same issue here. 
![image](https://cloud.githubusercontent.com/assets/1852180/15324381/d2aa9538-1c0b-11e6-9466-079f58f8342d.png)

**Comment by dasMulli** [comment]
You need to uninstall old version of the RC2 tooling. `dotnet --version` should show `1.0.0-preview1-002702`

**Comment by praseetht** [comment]
I'm also running into the same issue. I had previous version on runtimes which i removed using `dnvm uninstall` but VS 2015(Update 2) still doesn't allow me to build AspNetCore project 
:confused:

**Comment by macgyver76** [comment]
I've got same problem when changing sdk version in global.json file. My `dotnet` version is `1.0.0-preview1-002702`.

**Comment by dasMulli** [comment]
@praseetht @macgyver76: check that you have the following two packages installed (only! nothing else named "Microsoft .NET Core ...") via control panel > programs and features

* `Microsoft .NET Core 1.0.0 RC2 - SDK Preview 1 (x64)` version `1.0.0.2702` (you may have an x86 version. but not concurrent with x64 afaik.)
* `Microsoft .NET Core 1.0.0 RC2 - VS 2015 Tooling Preview 1` version `1.0.2513.14`

Note that `dnvm` is irrelevant as neither `dnvm` or `dnx`/`dnu` are used in RC2.

**Comment by macgyver76** [comment]
@dasMulli Yes, I have just the two of them, nothing else.

**Comment by dasMulli** [comment]
You can try to delete the `.xproj` files and just open the `project.json` file as a project (file > open > project/solution). That should generate a fresh `.xproj` file (however, you may run into https://github.com/aspnet/Tooling/issues/480 which you need to manually work around).
If that and a reboot doesn't solve it, you should maybe file a new issue.

**Comment by praseetht** [comment]
It finally worked. Thanks @dasMulli :+1: 
Here's what I did:
- Reinstalled Tooling 
- Did `dnvm uninstall` on all version of runtime
- Installed latest Nuget Manager Extension from https://dist.nuget.org/visualstudio-2015-vsix/v3.5.0-beta/NuGet.Tools.vsix (This was mentioned in the docs, but somehow I missed that)
- Deleted all old `.xprojs` and created new.

**Comment by macgyver76** [comment]
@praseetht How did you create new `xprojs` files?

**Comment by praseetht** [comment]
@macgyver76 Yes. I removed the old ones'

**Comment by bilal-fazlani** [comment]
You need to delete the old donet cli installed from control panel. Then reinstall new runtime. 
Doing this solved the issue for me without recreating projects.

**Comment by amcdnl** [comment]
Similar issue, its ashamed the installer doesn't auto upgrade the old rc2?

**Comment by blackhill** [comment]
Go to Programs and Features, find "Microsoft Dotnet CLI for Windows (1.0.0.XXXX" then unistall.

**Comment by tysonnero** [comment]
@blackhill Thanks, that was the culprit

**Comment by pbering** [comment]
@blackhill thanks, worked for me also

**Comment by badyalsk** [comment]
Thanks alot @blackhill . your solution worked for me.

**Comment by CharlesKuncheria** [comment]
To add: I had to uninstall the cli (from Programs and Features). Now of dotnet --version => I get "1.0.0-preview1-002702"

**Comment by andynormancx** [comment]
Took me a while to fix this, as I was looking for the wrong thing to install. I was searching for things with Core in their name, which was only finding the RC2 bits.

On my machine I had to uninstall something called "Microsoft Dotnet CLI for Windows (1.0.0.001598 )".

**Comment by PatrickMcvay** [comment]
Ok for the people that don't have the Microsoft Dotnet CLI for Windows on their machine. This is what I did and it seemed to fix the problem. Close Visual Studio, Open it again, Open the .NET core project, Go to the link to download when the error modal pops up, Download it again even if you already have it. Once done click run and then click repair. It should fix the problem for the moment, next go to Nuget Package Manager Console and run "dotnet restore" . That's all I had to do to fix my problem.

**Comment by kakins** [comment]
@PatrickMcvay I had the same issue not finding the Microsoft Dotnet CLI for Windows in Programs and Features.  However, I did close VS and reopened the project.  The packages began to restore and then everything built, the error went away.  I guess I should've thought about trying a package restore, but I'm just still getting used to the newness of everything :)  Thanks all

**Comment by eramella** [comment]
In case there is still someone, like me, that despite all of the above the "dotnet --version" command still shows the old one, delete the dotnet folder under c:\Program Files and reinstall RC2 preview1 for VS2015. That did for me.

**Comment by bedwar2** [comment]
For me, had to remove: Microsoft .Net Core 1.0.0 RC2 - Runtime (x64)

**Comment by bojingo** [comment]
I was having this issue in a VSTS CI build.  Simply running "dotnet restore" for each project was all it took for me (I was using a Visual Studio build task and expected Visual Studio to do the restore for me, just like it does when I do it manually).  Not the simplest error message to diagnose, particularly with the variety of methods listed above that people used to fix it.

**Comment by klaygomes** [comment]
This problem raises if you have two dotnet cli installed. Just type "where dotnet" in cmd, if it shows anything different from "C:\Program Files\dotnet\dotnet.exe" ; Uninstall Microsoft Dotnet CLI for Windows ( 1.0.0.00XXXX )

**Comment by tomtheisen** [comment]
I was able to resolve this issue in VS by running it as administrator.  I still don't know the root cause.

**Comment by hugoestr** [comment]
I ran into this problem with Visual Studio 2015 update 3. When I dotnet --version, I would get 1.0.0-Beta5. 

 I had to uninstall via the control panel all installs that related to dotnet core. Then I had to manually remove dnx, dotnet, and dnvm by hunting them down in the file system. Then I reinstalled core via dotnet-dev-win-x64.latest.exe and DotNetCore.1.0.0-SDK.Preview2-x64.exe . 

After that Visual Studio stopped giving me the error and the the console command "dotnet" began giving me  1.0.0-preview3-003117 as the current version.

**Comment by sravan1022** [comment]
No need to uninstall anything. Simply Open your global.json of your project and update it with the .NET Core SDK you have. It should solve it as it worked for me.

**Comment by mafshin** [comment]
I have the same problem. As @andynormancx mentioned, I was searching for "Core" names while I should remove the 'DotNet CLI' entries. When I removed both entries, everything became OK. Now I can build ASP.NET Core projects in Visual Studio.

**Comment by fabriciorissetto** [comment]
I just had to edit the `global.json` file of my solution to point to the version of my `dotnet --version`. The file now looks like this:

{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-preview2-003121"
  }
}

**Comment by krajek** [comment]
I tried everything, and only removing old DotNet CLI For Windows helped immediately.

**Comment by xMarkos** [comment]
I had only 1 version installed, no dotnet CLI and it didn't work from within Visual Studio but it did from command line. It might be obvious to some but I didn't realize we are living in a stone age - the trick was to reboot the computer after doing all the reinstallings.

**Comment by weedkiller** [comment]
**After updating to the latest it does not work for me!**

## I have this issue still NOT fixed, does not work.
In addition uninstalling a previous version fails to remove from windows


![image](https://cloud.githubusercontent.com/assets/21086190/20589069/e652cdf4-b1e7-11e6-8220-cbc9ede4c35b.png)


I tried to uninstall the `older Microsoft Core RC 1.0.1 VS tooling` and the `older Microsoft Core RC 1.0.1  SDK` , both show uninstall succeeded but its still there `older Microsoft Core RC 1.0.1 VS tooling` 

![image](https://cloud.githubusercontent.com/assets/21086190/20589234/3f062dfa-b1e9-11e6-9b72-4c82d4a6ae49.png)

**Comment by GrantErickson** [comment]
I just installed an older version based on this known issue with the tooling. https://github.com/aspnet/Tooling/blob/master/known-issues-vs2015.md#missing-sdk

It wasn't clear why an upgrade to the project wouldn't work. I couldn't get it to work by changing the tooling version in the global.json. However, installing 3121 did get me going again.

**Comment by AgentMC** [comment]
Never installed .NetCore before. Installed according to manual. Only one version is installed. VS 2015. Same error as @weedkiller has. dotnet restore + dotnet run works fine though :)

**Comment by weedkiller** [comment]
@AgentMC glad someone else sees this, I was going crazy, install, re-install, uninstall and reboot!!! 🎲 

Another issue is that uninstall from the programs and features or previous versions does not clean out the old versions.

**Comment by luntino** [comment]
Exactly the same issue as @weedkiller and @AgentMC I just cant get rid of that version of the SDK even though the uninstall completes. Did you guys ever get a fix?

**Comment by shawty** [comment]
HI All, just to add my 2p worth to this thread.

I got hit by this issue this morning (Previously my VS2015 was working perfectly) then I fired it up, and boom, this happened.

After a bit of detective work (And noticing some other things wrong in my system) I tracked it down to a piece of software I installed a few days ago.

The piece of software I installed had changed my system path to ONLY point to it's own directory, so there was NOTHING else in the path.  No windows system folders, none of my other programs, and crucially no DotNet/Framework/VS Cli paths or any of the usual stuff.

I'm going to see if I can do a system restore, if not I'll have to manually rake around my hard drive and put all of this back in manually (For the record I've lost Npm, Node, Gulp and all that stuff too)

The point I'm trying to make here, is this issue seems to be very dependent on which path points to where.

**Comment by drbergeron** [comment]
I've been running into this too. the solution for me was to run visual studio 2015 as administrator, then open the project. just double clicking the .sln to launch would cause the SDK error.

I'm running on a fairly locked down corporate laptop, for full disclosure.

**Comment by weedkiller** [comment]
Running in a**dmin mode for me is not an option, they need to fix this!!**
