### ISSUE TITLE
dotnet new - Failed to create prim the NuGet cache  (initial run!)

### ISSUE THREAD

**Issue by GorillaSpring** [dotnet/cli#4169]
## Steps to reproduce
I have tried to uninstall and reinstall all .net core installs.  Same behavior every time.

1) With Visual Studio Enterprise 2015 (Version 14.0.25425.01 Update 3)
  ** Note, I did repair the Update 3.3 just to see if that helped.
2) Download and installed the .NET Core 1.0.0 - VS 2015 Tooling Preview 2
3) Opened cmd prompt
4) "mkdir hwapp"
5) "cd hwapp"
6) "dotnet new"

** Notes, I did uninstall the Tooling Preview 2 and the .NET Core 1.0.0 - SDK Preview 2 (x64) and tried the dotnet-dev-win-x64.latests.exe (as of Sept 12th).   Output below is from that version.

## Expected  behavior
Install NuGet .Net core packages and create project files.

## Actual behavior

** this is the output from 1.0.1  (1.0.0 gives the same results, but does not log the error about the metadata. **

C:\dev\Tests\hwapp>dotnet --verbose new

Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.

Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include commandline arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.

Configuring...
-------------------
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 1858 ms
Expanding 100% 8996 ms
log  : Restoring packages for C:\Users\ben\AppData\Local\Temp\mqkvqdvn.bou\project.json...
error: An error occurred while retrieving package metadata for 'Microsoft.CodeAnalysis.CSharp.1.3.0' from source 'C:\Users\ben\.nuget\packages\'.
error:   '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
Failed to create prime the NuGet cache. restore failed with: 1
Telemetry is: Disabled
Created new C# project in C:\dev\Tests\hwapp.

## Environment data
`dotnet --info` output:

C:\dev\Tests\hwapp4>dotnet --info
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by GorillaSpring** [comment]
This was resolved by clearing my nuget cache.

Nice to have would be to output a suggestion to "clear nuget cache"

Issue can be closed.  

For reference to clear nuget cache: 

[http://stackoverflow.com/questions/30933277/how-to-clear-nuget-package-cache-using-command-line](url)

**Comment by aggieben** [comment]
I am experiencing this issue even after clearing `~/.nuget/*`.  There is also bizarre behavior I haven't figure out yet: I have RC4 installed, but when I run `dotnet --version`, it says 1.0.0-rc3-004530.

I have a dotnet-versions script in my path that prints the list of installed SDKs, and here's the output of that:
```
λ dotnet versions

Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.

Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include command-line arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.

Configuring...
-------------------
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 3374 ms
Expanding 100% 14863 ms
Failed to create prime the NuGet cache. new failed with: -1
1.0.0-preview2-003131
1.0.0-preview2-003133
1.0.0-preview2-1-003177
1.0.0-preview4-004233
1.0.0-rc3-004530
1.0.0-rc4-004771
```

I tried running the RC4 installer again just to see if it would repair something that had gone sideways somehow, but it didn't seem to help anything.

**Comment by fabioduque** [comment]
@tommed 
`nuget locals all -clear`

**Comment by DanJ210** [comment]
Yea, link broken and the suggested solution does not fix the issue.

This should be reopened.

**Comment by DanJ210** [comment]
I'm also getting this now. After removing dotnet core CLI's and installing the latest one. I'm getting this error,
`failed to create prime the nuget cache. new failed with -2147352571`

Before that it was 
`failed to create prime the nuget cache. new failed with 1`
