### ISSUE TITLE
Support for libicu 57 (default for Fedora 25)

### ISSUE THREAD

**Issue by mickaelistria** [dotnet/cli#4865]
## Steps to reproduce

On Fedora 25, install dotnet following instructions for Fedora 24

## Expected  behavior

`dotnet --version` works

## Actual behavior

`dotnet --version` returns `Failed to initialize CoreCLR, HRESULT: 0x80131500`, typical of wrong libicu, as reported in https://github.com/dotnet/cli/issues/3717 and others

**Comment by mickaelistria** [comment]
On Fedora 25, issue #2018 is still relevant.
I've tried some workarounds similar to the ones that worked for Fedora 24 (using different libicu and tweaking LD_LIBRARY_PATH) but so far without success.

**Comment by tmds** [comment]
@mickaelistria give this a try: https://github.com/dotnet/core/pull/326#issuecomment-262479168
In the meanwhile the rover tool was merged on master.

**Comment by piotrpMSFT** [comment]
@bartonjs

**Comment by mickaelistria** [comment]
Thanks @tmds . I managed to get dotnet working properly on Fedora 25. Can't wait to see rpms ;) #4866

**Comment by piotrpMSFT** [comment]
Sounds like this one is fixed and #4866 is what's remaining.

**Comment by victorperin** [comment]
Not fixed. Still having this issue on fedora 25. :/

**Comment by kellermanrivero** [comment]
Hi everyone, I found temporary workaround:

1. Get libicu-56 for Fedora 24
```wget ftp://fr2.rpmfind.net/linux/fedora/linux/releases/24/Everything/x86_64/os/Packages/l/libicu-56.1-4.fc24.x86_64.rpm```

2. Extract the rpm contents.
```rpm2cpio libicu-56.1-4.fc24.x86_64.rpm | cpio -idmv```

3. Move the required files
```sudo cp -v ./usr/lib64/* /usr/lib64 && rm -Rvf ./usr``` 

After that dotnet should work as expected.

**Comment by albertopatino** [comment]
@kellermanrivero Thanks! Workaround works for me !

**Comment by victorperin** [comment]
Can someone reopen this bug? It still happening, we don't have libicu 57 support.
