### ISSUE TITLE
"dotnet publish" for web app fails to complete when targeting "net46x" in VS 2017 RC

### ISSUE THREAD

**Issue by nateb19866** [dotnet/cli#5086]
I'm running the latest .NET 1.1 SDK (1.0.0-preview5-004275) and tools, and am receiving an error when trying to run "dotnet publish" on a ASP.NET Core web application. It builds without errors, and if I change "net462" to "net452" it publishes fine. It also published fine when targeting net462 before the migration from the project.json format to the csproj format. I discovered the error when migrating my Service Fabric application from VS 2015 to VS 2017, but soon realized it applied to all Core web apps and am able to reproduce it using the below approach.  I have a gist of a sample failing csproj file [here ](https://gist.github.com/nateb19866/43359acd0e3bd5e3e5fd6f7bd8d99a84)as well.

## Steps to reproduce

1. In VS 2017, add a new ASP.NET Core Web Application (either Web API or Web Application is fine)
2. Edit the  associated .csproj file, and change
```
<PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>
```
to
```
<PropertyGroup>
   <OutputType>Exe</OutputType>
      <TargetFramework>net462</TargetFramework>
      <PreserveCompilationContext>true</PreserveCompilationContext>
      <RuntimeIdentifier>win7-x64</RuntimeIdentifier>
  </PropertyGroup>
```

3. Remove the `<PackageReference Include="Microsoft.NETCore.App" Version="1.0.1" />` entry from the PackageReference section.
3. Build the project
4. Run dotnet publish. 

## Expected  behavior
It publishes successfully.

## Actual behavior

Receive the following error:
`C:\Program Files\dotnet\sdk\1.0.0-preview5-004275\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Publish.targets(128,5): error MSB3094: "DestinationFiles" refers to 1 item(s), and "SourceFiles" refers to 2 item(s). They must have the same number of items`

## Environment data
```
.NET Command Line Tools (1.0.0-preview5-004275)

Product Information:
 Version:            1.0.0-preview5-004275
 Commit SHA-1 hash:  f1c16e59d6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview5-004275
```

**Comment by livarcocc** [comment]
@mlorbetske This seems like an issue with the Web.Sdk template. Can you take a look?

**Comment by mlorbetske** [comment]
@vijayrkn can you take a look? There are no patterns defined in the `csproj` (which is the usual cause of the duplication) and nothing comes to mind why the behavior here would change for `net46x`.

**Comment by vijayrkn** [comment]
This is the only issue that we know of that repros in net 461 & 462 but does not repro in 451.
https://github.com/dotnet/sdk/issues/367

**Comment by nateb19866** [comment]
Looks like it might be related to this one: https://github.com/Microsoft/msbuild/issues/1345

Here's the relevant snippet of the verbose log when I run dotnet publish:
```
                     Task Parameter:
                         SourceFiles=
                             C:\Users\nbecker\.nuget\packages\system.io\4.1.0\ref\net462\System.IO.dll
                                     CopyLocal=false
                                     CopyToPublishDirectory=Always
                                     FusionName=System.IO, Version=4.1.0.0, Culture=neutral,PublicKeyToken=b03f5f7f11d50a3a
                                     ImageRuntime=v4.0.30319
                                     NuGetIsFrameworkReference=false
                                     NuGetSourceType=Package
                                     OriginalItemSpec=C:\Users\nbecker\.nuget\packages\system.io\4.1.0\ref\net461\System.IO.dll
                                     Private=false
                                     ReferenceSourceTarget=ResolveAssemblyReference
                                     RelativePath=refs\System.IO.dll
                                     ResolvedFrom={RawFileName}
                                     Version=4.1.0.0
                             C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\Facades\System.IO.dll
                                     CopyLocal=false
                                     CopyToPublishDirectory=Always
                                     RelativePath=refs\System.IO.dll
                                     ResolvedFrom=ImplicitlyExpandDesignTimeFacades
                                     WinMDFile=false (TaskId:160)
                     Task Parameter:DestinationFiles=bin\Debug\net462\win7-x64\publish\refs\System.IO.dll (TaskId:160)
                     Task Parameter:OverwriteReadOnlyFiles=False (TaskId:160)
10:13:13.841     1>C:\Program Files\dotnet\sdk\1.0.0-preview5-004275\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Publish.targets(128,5): error MSB3094: "DestinationFiles" refers to 1 item(s), and "SourceFiles" refers to 2 item(s). They must have the same number of items. [C:\Users\nbecker\Documents\Visual Studio 2017\Projects\WebApplication2\src\WebApplication2\WebApplication2.csproj]
```

**Comment by livarcocc** [comment]
@nateb19866 Any chance you can share your csproj here? It may be something else in your csproj as well.

**Comment by vijayrkn** [comment]
@nateb19866 Yes it looks like the same issue (Microsoft/msbuild#1345 was created for fixing this dotnet/sdk#367).

**Comment by nateb19866** [comment]
@livarcocc  - Yep!  It's here: https://gist.github.com/nateb19866/43359acd0e3bd5e3e5fd6f7bd8d99a84

**Comment by piotrpMSFT** [comment]
@vijayrkn looks like those issues are closed, and CLI currently has latest SDK. Is this fixed, then?

**Comment by vijayrkn** [comment]
Yes, this issue should be fixed. This is the actual bug tracking the work needed for this - https://github.com/Microsoft/msbuild/issues/1345

**Comment by nateb19866** [comment]
Yeah, I tried this with the latest SDKs, and it's working - thanks!

**Comment by velyo** [comment]
We still expreiencing same problem on asp.net core application targetting net462.
Here is our .csproj file

```
<Project ToolsVersion="15.0" Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net462</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.ComponentModel.DataAnnotations" />
    <Reference Include="System.Data" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="1.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.0-preview4-final" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="1.0.0-msbuild2-final" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0-msbuild2-final" />
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="1.0.0-msbuild2-final" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0-msbuild2-final" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Data\CodeFocus.DataAccess.Models\CodeFocus.DataAccess.Models.csproj" />
    <ProjectReference Include="..\..\Data\CodeFocus.DataAccess\CodeFocus.DataAccess.csproj" />
    <ProjectReference Include="..\..\Data\CodeFocus.Data\CodeFocus.Data.csproj" />
    <ProjectReference Include="..\..\Logging\src\CodeFocus.Logging\CodeFocus.Logging.csproj" />
  </ItemGroup>
</Project>
```

When publishing from VS 2017 RC we got next error:
DestinationFiles" refers to 1 item(s), and "SourceFiles" refers to 2 item(s). They must have the same number of items.

Running `dotnet publish` with verbose diagnostic, on `1.0.0-preview5-004262`, gave this problem highlighted

```
Task "Copy" (TaskId:269)
                     Task Parameter:
                         SourceFiles=
                             C:\Users\velio.ivanov.SCALEFOCUS\.nuget\packages\system.diagnostics.tracing\4.3.0\ref\net462\System.Diagnostics.Tracing.dll
                                     CopyLocal=false
                                     CopyToPublishDirectory=Always
                                     FusionName=System.Diagnostics.Tracing, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
                                     ImageRuntime=v4.0.30319
                                     NuGetIsFrameworkReference=false
                                     NuGetSourceType=Package
                                     OriginalItemSpec=C:\Users\velio.ivanov.SCALEFOCUS\.nuget\packages\system.diagnostics.tracing\4.3.0\ref\net462\System.Diagnostics.Tracing.dll
                                     Private=false
                                     ReferenceSourceTarget=ResolveAssemblyReference
                                     RelativePath=refs\System.Diagnostics.Tracing.dll
                                     ResolvedFrom={RawFileName}
                                     Version=4.1.1.0
                             C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\Facades\System.Diagnostics.Tracing.dll
                                     CopyLocal=false
                                     CopyToPublishDirectory=Always
                                     RelativePath=refs\System.Diagnostics.Tracing.dll
                                     ResolvedFrom=ImplicitlyExpandDesignTimeFacades
                                     WinMDFile=false (TaskId:269)
                     Task Parameter:DestinationFiles=..\..\.build\refs\System.Diagnostics.Tracing.dll (TaskId:269)
                     Task Parameter:OverwriteReadOnlyFiles=False (TaskId:269)
14:04:02.073     1>C:\Program Files\dotnet\sdk\1.0.0-preview5-004262\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Publish.targets(128,5): error MSB3094: "DestinationFiles" refers to 1 item(s), and "SourceFiles" refers to 2 item(s). They must have the same number of items. [P:\scalefocus\CodeFocus\CodeFocus\Services\CodeFocus.Services\CodeFocus.Services.csproj]
                     Output Item(s): FileWrites=..\..\.build\refs\System.Diagnostics.Tracing.dll (TaskId:269)
                   Done executing task "Copy" -- FAILED. (TaskId:269)
```

There it gets clear that while coping files it founds two sources for System.Diagnostics.Tracing.dll
One from .NET 4.6.2 and another one from dotnet core sdk packages cache.

Hope this helps.

**Comment by elepner** [comment]
We're still experiencing the same issue with the latest VS 2017 RC with failing Copy task "DestinationFiles" refers to 1 item(s), and "SourceFiles" refers to 2 item(s). They must have the same number of items..

**Comment by stevenshort** [comment]
Still getting this, anyone have a workaround?

**Comment by elepner** [comment]
Everything works perfectly for our .NET Core project targeting net461 since the VS17 release.

**Comment by stevenshort** [comment]
Ah, I've been looking a few different bugs. Mine is the same behavior but with packaging service fabric - not .net core - sorry
