### ISSUE TITLE
rebuild will be triggered based on the character case of the current working directory

### ISSUE THREAD

**Issue by duncanawoods** [dotnet/cli#5334]
This was discovered when using both visual studio and the CLI tools. Switching between the tools was  triggering a rebuild every time on a huge project without any source changes.

## Steps to reproduce

1. Start powershell prompt
2. cd c:\Users\\\<your user\>
3. mkdir scratch; 
4. cd scratch
5. dotnet new
6. dotnet restore
7. dotnet build
8. cd c:\users\\\<your user>\scratch
9. dotnet build
10. c:\Users\\\<your user>\scratch
11. dotnet build

n.b. cmd.exe is unaffected because it's cd does not seem to be case-sensitive so step 8. makes no change to cwd.

## Expected  behavior

Steps 9 and 11 both respond:

> Project scratch (.NETCoreApp,Version=v1.1) was previously compiled. Skipping compilation.

## Actual behavior

Steps 9 and 11 both respond:

> Project scratch (.NETCoreApp,Version=v1.1) will be compiled because Input items removed from last build
> Compiling scratch for .NETCoreApp,Version=v1.1
> 
> Compilation succeeded.
>     0 Warning(s)
>     0 Error(s)
> 
> Time elapsed 00:00:00.6166965

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
I'm quite confident that @blackdwarf is right that this issue is fixed by the migration to msbuild, but whould love to hear a confirmation from @duncanawoods.

@duncanawoods can I ask you to:
1. Install VS2017 RC from https://www.visualstudio.com/vs/visual-studio-2017-rc/
2. Install the latest cli from the home page of this repo
3. make a copy of your solution
4. `cd` into the copy directory and run `dotnet migrate`
5. Open the solution in Visual Studio 2017 RC

Do you still see the same incrementality conflict?

**Comment by duncanawoods** [comment]
@piotrpMSFT I heard the 2017 RC can break 2015 so had to create a VM... anyway have a bald yak now.

* I do not see separate CLI tools at your link so I have only used the VS2017 install
* I have to use "dotnet build -v:n" to see the difference between a build & rebuild on the CLI
* I still see the casing issue when just changing the path case in powershell
* In VS2017 something seems wrong - there is no difference between the build output with and without source changes even at detailed logging level. It just takes longer when there are source changes. It looks like it always calls csc.exe without doing anything other than click "build".

Note that I am grateful you have reduced verbosity of dotnet build but not indicating the difference between build and rebuild by default has IMHO gone too far - its a crucial sanity check for me e.g. did I actually change the file I thought I did. Especially useful when working on multiple branches so you have multiple copies of the same files and projects and its easy to change a .cs on the wrong branch and then spent 10 minutes testing nothing.

    dotnet --info
    .NET Command Line Tools (1.0.0-preview4-004233)
    
    Product Information:
     Version:            1.0.0-preview4-004233
     Commit SHA-1 hash:  8cec61c6f7
    
    Runtime Environment:
     OS Name:     Windows
     OS Version:  10.0.14393
     OS Platform: Windows
     RID:         win10-x86
     Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004233

**Comment by duncanawoods** [comment]
Ok just seen you wanted me to install the CLI tools from this repo. I have just tried this but the installer fails with this error:

    0x80070001 - Incorrect function

**Comment by duncanawoods** [comment]
[error.txt](https://github.com/dotnet/cli/files/716119/error.txt)

**Comment by piotrpMSFT** [comment]
what a useful~less~ error message and log we produced...

by chance was insaller running from a non-elevated process?

**Comment by duncanawoods** [comment]
It was run in normal conditions on a fresh VM. Just ran again with "run as administrator", same result.

**Comment by livarcocc** [comment]
We have made some good improvements to the installer lately and things have changed considerably with the msbuild transition. I am closing this issue for now. Please, re-activate if you still hit this in the latest CLI.
