### ISSUE TITLE
'dotnet new console' fails with '2.0.0-preview3-006607' .NET Command Line Tools

### ISSUE THREAD

**Issue by daxian-dbw** [dotnet/cli#7013]
## Steps to reproduce
`dotnet new console`

## Expected  behavior
No error and successfully restored

## Actual behavior
```
PS:52> dotnet new console
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on C:\Arena\Apps\dotnet2\bb\bb.csproj...
  Restoring packages for C:\Arena\Apps\dotnet2\bb\bb.csproj...
C:\Users\usr\AppData\Local\Microsoft\dotnet\sdk\2.0.0-preview3-006607\NuGet.targets(102,5): error : 
Failed to retrieve information about 'Microsoft.NETCore.App' from remote source 'C:\Users\usr\.dotnet\NuGetFallbackFolder'. [C:\Arena\Apps\dotnet2\bb\bb.csproj]


Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'

PS:53> dotnet restore
  Restoring packages for C:\Arena\Apps\dotnet2\bb\bb.csproj...
C:\Users\usr\AppData\Local\Microsoft\dotnet\sdk\2.0.0-preview3-006607\NuGet.targets(102,5): error : 
Failed to retrieve information about 'Microsoft.NETCore.App' from remote source 'C:\Users\usr\.dotnet\NuGetFallbackFolder'. [C:\Arena\Apps\dotnet2\bb\bb.csproj]
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0-preview3-006607)

Product Information:
 Version:            2.0.0-preview3-006607
 Commit SHA-1 hash:  81dd304f72

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\usr\AppData\Local\Microsoft\dotnet\sdk\2.0.0-preview3-006607\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview3-25426-01
  Build    : 122309e7e7fb9bb233fe4910f822c28ec73f0957
```

**Comment by JonathanLoscalzo** [comment]
this happens for all templates too :(

**Comment by JonathanLoscalzo** [comment]
maybe [this issue](https://github.com/dotnet/cli/issues/3330) solve the problem?

Create a nuget.config local,
add => 
<add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" /> 

it solve my problem... or I think so

**Comment by livarcocc** [comment]
@JonathanLoscalzo, look under %appdata%/NuGet/NuGet.Config and remove any references to CLIFallbackFolder from it. This is an entry that we no longer need in preview3. If you do that, you will get the real error, which is that we can't find the M.NC.App package. The reason for that is that the runtime between the CLI and asp.net are out of sync and when that happens, you need the feed above.

Still, I am moving this issue to NuGet, I don't think NuGet should say that it failed to find the package on that feed if the folder is empty, it should just say that it failed to find the package.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5504

**Comment by daxian-dbw** [comment]
@livarcocc thanks for the reply. Is there a working `2.0.0-preview3` .NET CLI now? If there is one, can you please share the exact version?

**Comment by livarcocc** [comment]
You can work around this issue by adding '<add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />' to your NuGet.Config. Given that, any preview3 CLI should be working.

**Comment by daxian-dbw** [comment]
In my case, I always have a `NuGet.Config` file in the parent folder that contains the dotnet-core feed and it doesn't work. I also tried moving the `NuGet.Config` to the same folder, and it still doesn't work.
Structure of the 'Test' folder:
```
PS:36> tree . /F
C:\ARENA\APPS\TEST
    NuGet.config
    Program.cs
    Test.csproj
```
Content of `NuGet.Config`:
```
PS:40> cat .\NuGet.config
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="powershell-core" value="https://powershell.myget.org/F/powershell-core/api/v3/index.json" />
  </packageSources>
</configuration>
```
Content of `Test.csproj`:
```
PS:42> cat .\Test.csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

</Project>
```
Then running `dotnet restore` fails in the folder:
```
PS:44> C:\Users\usr\Downloads\dotnet-sdk-latest-win-x64\dotnet.exe restore
  Restoring packages for C:\Arena\Apps\Test\Test.csproj...
C:\Users\usr\Downloads\dotnet-sdk-latest-win-x64\sdk\2.0.0-preview3-006607\NuGet.targets(102,5): 
error : Failed to retrieve information about 'Microsoft.NETCore.App' from remote source 'C:\Users\usr\.dotnet\NuGetFallbackFolder'. [C:\Arena\Apps\Test\Test.csproj]
```
The `dotnet --info`:
```
PS:45> C:\Users\usr\Downloads\dotnet-sdk-latest-win-x64\dotnet.exe --info
.NET Command Line Tools (2.0.0-preview3-006607)

Product Information:
 Version:            2.0.0-preview3-006607
 Commit SHA-1 hash:  81dd304f72

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\usr\Downloads\dotnet-sdk-latest-win-x64\sdk\2.0.0-preview3-006607\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview3-25426-01
  Build    : 122309e7e7fb9bb233fe4910f822c28ec73f0957
```

**Comment by daxian-dbw** [comment]
@livarcocc Could you please comment? Moving the NuGet.config file to the same folder doesn't work for me, and I see the same problem with `2.0.0-preview3-006609`. This is on a win10 clean machine without `%appdata%/NuGet` folder.
