### ISSUE TITLE
dotnet commands keep prompting welcome text even if it is not the first time to run on a cmd shell

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/cli#7016]
## Steps to reproduce
- md consoleApp1;
- cd consoleApp1;
- dotnet new console;
- dontet restore;
- dotnet build;
- dotnet run;

## Expected  behavior
all dotnet commands run succeeded with no errors or warnings, welcome text only prompts for the first time to run dotnet command on a cmd shell.

## Actual behavior
all dotnet commands print duplicate text info:
```
Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.

Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include command-line arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.

Configuring...
-------------------
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 3444 ms
Expanding 100% 3832 ms
Failed to create prime the NuGet cache. restore failed with: 1
```
In addition: 
Test .net core mstest, xunit, mvc or class lib or mvc project from CLI with the same issue, neither C# nor F#.

## Product info
Install d15prerel.26627.3003  (bootstrappers\Enterprise)
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.1.0-preview1-005051)

Product Information:
 Version:            1.1.0-preview1-005051
 Commit SHA-1 hash:  5e88564e56

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.1.0-preview1-005051
```

**Comment by MiaomiaoHuangfu** [comment]
Install d15prerel.26627.3003 of bootstrappers\BuildTools, select Web Tool Bundle workload;
Test mvc from CLI, with the same issue.

**Comment by livarcocc** [comment]
This has been fixed and inserted into VS. Please, try tonight's build and re-activate if this still repros.

**Comment by ngbrown** [comment]
I am experiencing this same behavior, with the same version (1.1.0-preview1-005051) of the `dotnet` tool by installing Visual Studio 2017.3 Preview (15.3.26621.02) on a fresh Windows 10 install.

Downloading and installing the latest dotnet sdk (2.1.0-preview1-006635) didn't resolve this.  It didn't try to restore the offline packages and fails on `dotnet new console`

```
PS C:\dev\test> dotnet new console
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on C:\dev\test\test.csproj...
  Restoring packages for C:\dev\test\test.csproj...
C:\dev\test\test.csproj : error NU1102: Unable to find package Microsoft.NETCore.App with version (>= 2.0.0-preview3-25426-01)
C:\dev\test\test.csproj : error NU1102:   - Found 13 version(s) in nuget.org [ Nearest version: 2.0.0-preview2-25407-01 ]
C:\dev\test\test.csproj : error NU1102:   - Found 6 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 1.1.2 ]
  Generating MSBuild file C:\dev\test\obj\test.csproj.nuget.g.props.
  Generating MSBuild file C:\dev\test\obj\test.csproj.nuget.g.targets.
  Restore failed in 917.11 ms for C:\dev\test\test.csproj.


Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'
```

**Comment by livarcocc** [comment]
@ngbrown what you are seeing is actually different. You picked up a version of the preview3 of the CLI. This version of the CLI requires you to add a NuGet.Config with `<add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />` in the package sources, because the offline cache does not contain all the packages.

**Comment by ngbrown** [comment]
@livarcocc you [had said](https://github.com/dotnet/cli/issues/7016#issuecomment-312149803) try last night's build, and that was the only build I found (https://github.com/dotnet/cli).  So maybe I should ask where is the build you are referring to.

**Comment by livarcocc** [comment]
For the first run experience problem, it is a build under rel/1.1.0 branch. For 2.0. our builds are under release/2.0.0. If you want the latest 2.0 preview build that we officially release, you can get that here: https://www.microsoft.com/net/core/preview

**Comment by ngbrown** [comment]
The URL's on that page (https://github.com/dotnet/cli/tree/rel/1.1.0) all point installers and version files for release 1.0.1.  The `README.md` in the rel/1.1.0 branch needs updated.

**Comment by ngbrown** [comment]
I got the `dotnet` cli version `1.1.0-preview1-005051` from installing Visual Studio 2017.3 from (https://www.visualstudio.com/vs/preview/), so I wasn't clear on where the bits and pieces were to fix problems like this.

**Comment by ngbrown** [comment]
The latest build at https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.1.0/dotnet-dev-win-x64.latest.exe is 1.1.0.5045, even older than what was packaged with Visual Studio 2017.3 Preview.  Installing it didn't resolve anything.

What is the exact URL to get nightly builds?

**Comment by MiaomiaoHuangfu** [comment]
The issue is regression on d15rel.26724.00.
dotnet --version: 1.1.0-preview1-005098
