### ISSUE TITLE
.NET Core SDK 2.1.2 

### ISSUE THREAD

**Issue by qqbuby** [dotnet/cli#8177]
Visual Studio 2017 15.5 has been released, and along with the `.NET Command Line Tools (2.1.2)` , however what I want to known where can we download  the standalone `.NET Command Line Tools (2.1.2)`  ?

**Comment by livarcocc** [comment]
cc @leecow

**Comment by markusschaber** [comment]
we'd need the 32 bit version, as we currently have some 32-bit only native code... (It's being ported by the other team, but takes some time...)

**Comment by livarcocc** [comment]
This has been fixed a few days ago actually.

**Comment by markusschaber** [comment]
https://github.com/dotnet/core/tree/master/release-notes still lists "2.0.3" as latest release...

**Comment by bergmeister** [comment]
Why was it needed to bump the minor version? This will just add to the versioning mess of .Net Core tooling. Why can the SDK not match the maximum .Net Core version?

**Comment by livarcocc** [comment]
@bergmeister because the SDK has reasons to change beyond the runtime. In this case, we took a new version of Roslyn to enable C# 7.2 and we also took a number of perf improvements across the board that would not fit within a patch update.

**Comment by bergmeister** [comment]
I still don't see how this 'advantage' makes up for the complexity/confusion when talking about versioning, I see only as trying to be purist about semantic versioning. I always need to draw a table when doing various investigations where different versions of SDK/Runtime contain certain bugs.  Taking that aside, Microsoft needs to ensure that it is clear what is in a package. The [download](https://www.microsoft.com/net/download/windows) page is absolutely not helpful in showing me what is in the package. I have to go to the GitHub [releases](https://github.com/dotnet/cli/releases) and the only additonal information is the Runtime version. The re-design of the website has made it so much worse.

**Comment by simeyla** [comment]
@livarcocc then can you please explain that on the download page https://www.microsoft.com/net/download/windows

It's insanely confusing - especially when 2.1 is about to be released and then you install it looking for new 2.1 features and they aren't there.

**Comment by livarcocc** [comment]
Which is why we are doing this: https://github.com/dotnet/designs/pull/29

The Major.Minor versions of the Runtime and the SDK will from now on be aligned. We did this by abandoning semantic versioning in the SDK. But it is much better explained in the link above.

**Comment by 6D65** [comment]
@livarcocc sorry, this might not be the best place to ask, but you mentioned that SDK 2.1.2 got the latest version of Roslyn and it should support C# 7.2, but this doesn't seem to be the case.

Am I missing something?
I've installed the latest Win 64bit SDK(`2.1.4`) as well as separately `2.1.2`, and none of them are able to compile a ReadOnlySpan<T>.

```
PS C:\Users\username\projects\project-cs> dotnet --version
2.1.2
PS C:\Users\username\projects\project-cs> dotnet build
Microsoft (R) Build Engine version 15.5.179.9764 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 15.02 ms for C:\Users\username\projects\project-cs\ProjectCS.csproj.
Program.cs(15,26): error CS0246: The type or namespace name 'ReadOnlySpan<>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\username\projects\project-cs\ProjectCS.csproj]

Build FAILED.

Program.cs(15,26): error CS0246: The type or namespace name 'ReadOnlySpan<>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\username\projects\project-cs\ProjectCS.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.98
PS C:\Users\username\projects\project-cs>
```

**Comment by markusschaber** [comment]
@6D65 As far as I know, `ReadOnlySpan<T>` is only shipped with .NET Core 2.1, not with .NET Core 2.0. The 2.1 SDK still works against .NET Core 2.0 currently, as .NET Core 2.1 is not released yet.

AFAICS, you can try the System.Memory NuGet Package for a backport. Note, however, that you'll need .NET Core 2.1 or a future .NET 4.X to fully benefit from the improved performance.

**Comment by 6D65** [comment]
Thank you, @markusschaber , I was under impression that this should be already shipped as a part of C# 7.2 and it's available already in .NET Core 2.0. Will play around with the System.Memory NuGet package, for now, to master the API.

**Comment by markusschaber** [comment]
@6D65 You need C# 7.2 support in the compiler to use those new features, that's why the compiler shipped before the runtime changes, so the devs can use the compiler to actually implement all the new APIs using `Span<>` in the runtime libraries :-)

**Comment by 6D65** [comment]
@markusschaber great, thank you for explaining me. Cannot wait for NET Core 2.1, exiting stuff.
