### ISSUE TITLE
dotnet run: Access to path... AppData\Local\Application Data is denied

### ISSUE THREAD

**Issue by tzwlai** [dotnet/cli#845]
Filing this on behalf of @bendono from https://github.com/dotnet/coreclr/issues/2590:

Following the .NET Core installation instructions for Windows, I issue the command "dotnet run". This results in the following error: Access to path... AppData\Local\Application Data is denied

![dotnet_error](https://cloud.githubusercontent.com/assets/846533/12213548/93aa118c-b6bd-11e5-9212-a35f48b190be.png)

Path: https://dotnet.github.io/getting-started/

Note that running PowerShell as an Admin does not help, either.
Not sure if it is related, but I notice that the restore and run are trying to use my user account from the C: drive. My user account is defined to be on D:. Should this use the defined user path, or is it hard-coded to C:?

**Comment by anurse** [comment]
Can you post the output of `dotnet -v run`?

**Comment by bendono** [comment]
Here is the output:
![dotnet_run](https://cloud.githubusercontent.com/assets/846533/12366815/ecd40584-bc20-11e5-8004-c3abd5cd9572.png)

**Comment by bendono** [comment]
I checked the path given in the output above.
I notice that C:\Users\Ben\bin\.dotnetrun\bf9df5e28144428fa371533fb314a325 is an empty folder.

**Comment by anurse** [comment]
Yeah, it hasn't been able to compile the project yet so there's nothing there. Can you access the folder in question (`C:\Users\Ben\AppData\Local\Application Data`) via explorer? I'm not sure what would actually be trying to read/write there...

**Comment by bendono** [comment]
The path up to C:\Users\Ben\AppData\Local exists.
However, there is no "Application Data" path.
Would you like me to manually create it?

**Comment by bendono** [comment]
@anurse Let me know if you need any other information from me.
Also, I'll be happy to test any fixes if needed.

**Comment by anurse** [comment]
Sorry @bendono, it's been a bit crazy with other stuff right now :). I'm not sure where the `Application Data` path is coming from, but if we're assuming the path exists and it doesn't, that might be part of the problem. You could try creating it, but I would definitely say that is a workaround rather than a fix :). You shouldn't have to create the folder, and it's possible it's a special folder that has to be created with certain permissions. It might be worth quickly creating it and trying again, then removing it after you try.

**Comment by siioko** [comment]
I ran into the same issue while trying to get started with .NET Core on my Windows 7 Pro PC. As a workaround, I changed the path in PowerShell from `C:\Users\myusername` to a newly created folder, `C:\netcore` for instance. From then on the `new`, `restore` and `run` commands worked faultlessly. 

(I'm new here so I don't really know if it's the right place to post workarounds, so sorry for any disturbance)

**Comment by bendono** [comment]
@anatay Sorry for the delay. I got a bit busy, too. Checking a little further, the folder "Application Data" does in fact exist, but by default it is not accessible. It is a virtual junction created for compatibility. While it is possible to take ownership of it, it is just a redirect to %APPDATA%. (On Windows Vista and up, this should be Users\<name>\AppData\Roaming.)
Perhaps the way that %APPDATA% is resolved is triggering some kind of compatibility that turns this into <user>\Application Data?

As noted above, changing to another folder (other than Users\<name>\) works around this issue. But I am not sure if this is really the real fix for this, though.

**Comment by xavirm** [comment]
I'm having the same problem in Windows 10 using .NET Core 1.0.0 - SDK Preview 2 , has been a development since then ? Thnx!

**Comment by siioko** [comment]
Je suis absent(e) du bureau jusqu'au 06/07/2016




Remarque : ceci est une réponse automatique à votre message  "Re:
[dotnet/cli] dotnet run: Access to path... AppData\Local\Application Data
is denied (#845)" envoyé le 04/07/2016 14:56:28.

C'est la seule notification que vous recevrez pendant l'absence de cette
personne.

**Comment by piotrpMSFT** [comment]
@xavirm can you show a full repro of what you're seeing? There has been significant progress on NuGet since this issue was opened and I'm surprised you're still seeing problems.

**Comment by jonico** [comment]
For me things started to work once I ran the command out of the repository with a solution file instead my home directory.
@tzwlai @xavirm ☝️ 

@piotrpMSFT @anurse: while the [documentation](https://dotnet.github.io/getting-started/) states that one should cd into the project, the errors in the VS console do not mention this:

![image](https://cloud.githubusercontent.com/assets/1872314/18786335/a66f34fe-819d-11e6-8849-b8893aa47be1.png)

**Comment by piotrpMSFT** [comment]
Thanks @jonico. I'm not able to reproduce this more generally so it seems like a local config issue. I'm going to close this. If someone hits it on preview3+ please open a new issue. Thanks for the workaround!
